export const SankeyOrder = [
  ["Nuclear","Thermal Generation"],
  ["Environmental Heat","Buildings Heat"],
  ["Environmental Heat","Thermal Generation"],
  ["Solar","Electricity"],["Wind","Electricity"],
  ["Other Renewables","Electricity"],
  ["Interconnectors","Electricity"],
  ["Waste","Bio Conversion"],
  ["Waste","Thermal Generation"],
  ["UK Biomass","Bio Conversion"],
  ["UK Biomass","Exports"],
  ["Bioenergy Imports","Bio Conversion"],
  ["Hydrogen Imports","Hydrogen Production"],
  ["Natural Gas","Hydrogen Production"],
  ["Natural Gas","Thermal Generation"],
  ["Natural Gas","Fossil Fuel Processing"],
  ["Natural Gas","Non energy use"],
  ["Natural Gas","Gas Grid Distribution"],
  ["Oil","Buildings Heat"],
  ["Oil","Industry"],
  ["Oil","Agriculture"],
  ["Oil","Light Vehicles"],
  ["Oil","Heavy Vehicles"],
  ["Oil","Aviation"],
  ["Oil","Fossil Fuel Processing"],
  ["Oil","Non energy use"],
  ["Coal","Thermal Generation"],
  ["Coal","Buildings Heat"],
  ["Coal","Industry"],
  ["Coal","Fossil Fuel Processing"],
  ["Coal","Non energy use"],
  ["Bio Conversion","Hydrogen Production"],
  ["Bio Conversion","Thermal Generation"],
  ["Bio Conversion","Buildings Heat"],
  ["Bio Conversion","Industry"],
  ["Bio Conversion","Agriculture"],
  ["Bio Conversion","Light Vehicles"],
  ["Bio Conversion","Heavy Vehicles"],
  ["Bio Conversion","Aviation"],
  ["Bio Conversion","Fossil Fuel Processing"],
  ["Bio Conversion","Gas Grid Distribution"],
  ["Thermal Generation","Electricity"],
  ["Thermal Generation","Buildings Heat"],
  ["Electricity","Hydrogen Production"],
  ["Electricity","GHG Removal"],
  ["Electricity","Thermal Generation"],
  ["Electricity","Buildings Heat"],
  ["Electricity","Buildings Appliances"],
  ["Electricity","Industry"],
  ["Electricity","Agriculture"],
  ["Electricity","Light Vehicles"],
  ["Electricity","Heavy Vehicles"],
  ["Electricity","Aviation"],
  ["Electricity","Fossil Fuel Processing"],
  ["Hydrogen Production","Light Vehicles"],
  ["Hydrogen Production","Heavy Vehicles"],
  ["Hydrogen Production","Gas Grid Distribution"],
  ["Gas Grid Distribution","Buildings Heat"],
  ["Gas Grid Distribution","Buildings Appliances"],
  ["Gas Grid Distribution","Thermal Generation"],
  ["Gas Grid Distribution","Agriculture"],
  ["Gas Grid Distribution","Industry"],
  ["Gas Grid Distribution","Fossil Fuel Processing"],
  ["Natural Gas","Losses"],
  ["Bio Conversion","Losses"],
  ["Thermal Generation","Losses"],
  ["Electricity","Losses"],
  ["Hydrogen Production","Losses"],
  ["Gas Grid Distribution","Losses"]
];

//mild improvement
// ["Nuclear","Thermal Generation"],
// ["Environmental Heat","Buildings Heat"],
// ["Environmental Heat","Thermal Generation"],
// ["Solar","Electricity"],["Wind","Electricity"],
// ["Other Renewables","Electricity"],
// ["Interconnectors","Electricity"],
// ["Waste","Bio Conversion"],
// ["Waste","Thermal Generation"],
// ["UK Biomass","Bio Conversion"],
// ["UK Biomass","Exports"],
// ["Bioenergy Imports","Bio Conversion"],
// ["Hydrogen Imports","Hydrogen Production"],
// ["Natural Gas","Hydrogen Production"],
// ["Natural Gas","Thermal Generation"],
// ["Natural Gas","Fossil Fuel Processing"],
// ["Natural Gas","Losses"],
// ["Natural Gas","Non energy use"],
// ["Natural Gas","Gas Grid Distribution"],
// ["Oil","Buildings Heat"],
// ["Oil","Industry"],
// ["Oil","Agriculture"],
// ["Oil","Light Vehicles"],
// ["Oil","Heavy Vehicles"],
// ["Oil","Aviation"],
// ["Oil","Fossil Fuel Processing"],
// ["Oil","Non energy use"],
// ["Coal","Thermal Generation"],
// ["Coal","Buildings Heat"],
// ["Coal","Industry"],
// ["Coal","Fossil Fuel Processing"],
// ["Coal","Non energy use"],
// ["Bio Conversion","Hydrogen Production"],
// ["Bio Conversion","Thermal Generation"],
// ["Bio Conversion","Buildings Heat"],
// ["Bio Conversion","Industry"],
// ["Bio Conversion","Agriculture"],
// ["Bio Conversion","Light Vehicles"],
// ["Bio Conversion","Heavy Vehicles"],
// ["Bio Conversion","Aviation"],
// ["Bio Conversion","Fossil Fuel Processing"],
// ["Bio Conversion","Losses"],
// ["Bio Conversion","Gas Grid Distribution"],
// ["Thermal Generation","Electricity"],
// ["Thermal Generation","Losses"],
// ["Thermal Generation","Buildings Heat"],
// ["Electricity","Hydrogen Production"],
// ["Electricity","GHG Removal"],
// ["Electricity","Thermal Generation"],
// ["Electricity","Buildings Heat"],
// ["Electricity","Buildings Appliances"],
// ["Electricity","Industry"],
// ["Electricity","Agriculture"],
// ["Electricity","Light Vehicles"],
// ["Electricity","Heavy Vehicles"],
// ["Electricity","Aviation"],
// ["Electricity","Fossil Fuel Processing"],
// ["Electricity","Losses"],
// ["Hydrogen Production","Light Vehicles"],
// ["Hydrogen Production","Heavy Vehicles"],
// ["Hydrogen Production","Losses"],
// ["Hydrogen Production","Gas Grid Distribution"],
// ["Gas Grid Distribution","Buildings Heat"],
// ["Gas Grid Distribution","Buildings Appliances"],
// ["Gas Grid Distribution","Thermal Generation"],
// ["Gas Grid Distribution","Agriculture"],
// ["Gas Grid Distribution","Industry"],
// ["Gas Grid Distribution","Fossil Fuel Processing"],
// ["Gas Grid Distribution","Losses"]

// ["Nuclear","Thermal Generation"],
// ["Environmental Heat","Buildings Heat"],
// ["Environmental Heat","Thermal Generation"],
// ["Solar","Electricity"],["Wind","Electricity"],
// ["Other Renewables","Electricity"],
// ["Interconnectors","Electricity"],
// ["Waste","Bio Conversion"],
// ["Waste","Thermal Generation"],
// ["UK Biomass","Bio Conversion"],
// ["UK Biomass","Exports"],
// ["Bioenergy Imports","Bio Conversion"],
// ["Hydrogen Imports","Hydrogen Production"],
// ["Natural Gas","Hydrogen Production"],
// ["Natural Gas","Thermal Generation"],
// ["Natural Gas","Fossil Fuel Processing"],
// ["Natural Gas","Non energy use"],
// ["Natural Gas","Gas Grid Distribution"],
// ["Natural Gas","Losses"],
// ["Oil","Buildings Heat"],
// ["Oil","Industry"],
// ["Oil","Agriculture"],
// ["Oil","Light Vehicles"],
// ["Oil","Heavy Vehicles"],
// ["Oil","Aviation"],
// ["Oil","Fossil Fuel Processing"],
// ["Oil","Non energy use"],
// ["Coal","Thermal Generation"],
// ["Coal","Buildings Heat"],
// ["Coal","Industry"],
// ["Coal","Fossil Fuel Processing"],
// ["Coal","Non energy use"],
// ["Bio Conversion","Hydrogen Production"],
// ["Bio Conversion","Thermal Generation"],
// ["Bio Conversion","Buildings Heat"],
// ["Bio Conversion","Industry"],
// ["Bio Conversion","Agriculture"],
// ["Bio Conversion","Light Vehicles"],
// ["Bio Conversion","Heavy Vehicles"],
// ["Bio Conversion","Aviation"],
// ["Bio Conversion","Fossil Fuel Processing"],
// ["Bio Conversion","Gas Grid Distribution"],
// ["Bio Conversion","Losses"],
// ["Thermal Generation","Electricity"],
// ["Thermal Generation","Buildings Heat"],
// ["Thermal Generation","Losses"],
// ["Electricity","Hydrogen Production"],
// ["Electricity","GHG Removal"],
// ["Electricity","Thermal Generation"],
// ["Electricity","Buildings Heat"],
// ["Electricity","Buildings Appliances"],
// ["Electricity","Industry"],
// ["Electricity","Agriculture"],
// ["Electricity","Light Vehicles"],
// ["Electricity","Heavy Vehicles"],
// ["Electricity","Aviation"],
// ["Electricity","Fossil Fuel Processing"],
// ["Electricity","Losses"],
// ["Hydrogen Production","Light Vehicles"],
// ["Hydrogen Production","Heavy Vehicles"],
// ["Hydrogen Production","Gas Grid Distribution"],
// ["Hydrogen Production","Losses"],
// ["Gas Grid Distribution","Buildings Heat"],
// ["Gas Grid Distribution","Buildings Appliances"],
// ["Gas Grid Distribution","Thermal Generation"],
// ["Gas Grid Distribution","Agriculture"],
// ["Gas Grid Distribution","Industry"],
// ["Gas Grid Distribution","Fossil Fuel Processing"],
// ["Gas Grid Distribution","Losses"]

// original
// ["Nuclear","Thermal Generation"],
// ["Environmental Heat","Buildings Heat"],
// ["Environmental Heat","Thermal Generation"],
// ["Solar","Electricity"],["Wind","Electricity"],
// ["Other Renewables","Electricity"],
// ["Interconnectors","Electricity"],
// ["Waste","Bio Conversion"],
// ["Waste","Thermal Generation"],
// ["UK Biomass","Bio Conversion"],
// ["UK Biomass","Exports"],
// ["Bioenergy Imports","Bio Conversion"],
// ["Hydrogen Imports","Hydrogen Production"],
// ["Natural Gas","Hydrogen Production"],
// ["Natural Gas","Thermal Generation"],
// ["Natural Gas","Fossil Fuel Processing"],
// ["Natural Gas","Losses"],
// ["Natural Gas","Non energy use"],
// ["Natural Gas","Gas Grid Distribution"],
// ["Oil","Buildings Heat"],
// ["Oil","Industry"],
// ["Oil","Agriculture"],
// ["Oil","Light Vehicles"],
// ["Oil","Heavy Vehicles"],
// ["Oil","Aviation"],
// ["Oil","Fossil Fuel Processing"],
// ["Oil","Non energy use"],
// ["Coal","Thermal Generation"],
// ["Coal","Buildings Heat"],
// ["Coal","Industry"],
// ["Coal","Fossil Fuel Processing"],
// ["Coal","Non energy use"],
// ["Bio Conversion","Hydrogen Production"],
// ["Bio Conversion","Thermal Generation"],
// ["Bio Conversion","Buildings Heat"],
// ["Bio Conversion","Industry"],
// ["Bio Conversion","Agriculture"],
// ["Bio Conversion","Light Vehicles"],
// ["Bio Conversion","Heavy Vehicles"],
// ["Bio Conversion","Aviation"],
// ["Bio Conversion","Fossil Fuel Processing"],
// ["Bio Conversion","Losses"],
// ["Bio Conversion","Gas Grid Distribution"],
// ["Thermal Generation","Electricity"],
// ["Thermal Generation","Losses"],
// ["Thermal Generation","Buildings Heat"],
// ["Electricity","Hydrogen Production"],
// ["Electricity","GHG Removal"],
// ["Electricity","Thermal Generation"],
// ["Electricity","Buildings Heat"],
// ["Electricity","Buildings Appliances"],
// ["Electricity","Industry"],
// ["Electricity","Agriculture"],
// ["Electricity","Light Vehicles"],
// ["Electricity","Heavy Vehicles"],
// ["Electricity","Aviation"],
// ["Electricity","Fossil Fuel Processing"],
// ["Electricity","Losses"],
// ["Hydrogen Production","Light Vehicles"],
// ["Hydrogen Production","Heavy Vehicles"],
// ["Hydrogen Production","Losses"],
// ["Hydrogen Production","Gas Grid Distribution"],
// ["Gas Grid Distribution","Buildings Heat"],
// ["Gas Grid Distribution","Buildings Appliances"],
// ["Gas Grid Distribution","Thermal Generation"],
// ["Gas Grid Distribution","Agriculture"],
// ["Gas Grid Distribution","Industry"],
// ["Gas Grid Distribution","Fossil Fuel Processing"],
// ["Gas Grid Distribution","Losses"]
